name: build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wifi-camera
        uses: ./.github/actions/build
